#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyXeMay")]
	public partial class QuanLyXeMayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertCTPHIEUNHAP(CTPHIEUNHAP instance);
    partial void UpdateCTPHIEUNHAP(CTPHIEUNHAP instance);
    partial void DeleteCTPHIEUNHAP(CTPHIEUNHAP instance);
    partial void InsertCTPHIEUXUAT(CTPHIEUXUAT instance);
    partial void UpdateCTPHIEUXUAT(CTPHIEUXUAT instance);
    partial void DeleteCTPHIEUXUAT(CTPHIEUXUAT instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIXE(LOAIXE instance);
    partial void UpdateLOAIXE(LOAIXE instance);
    partial void DeleteLOAIXE(LOAIXE instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUBAOHANH(PHIEUBAOHANH instance);
    partial void UpdatePHIEUBAOHANH(PHIEUBAOHANH instance);
    partial void DeletePHIEUBAOHANH(PHIEUBAOHANH instance);
    partial void InsertPHIEUNHAP(PHIEUNHAP instance);
    partial void UpdatePHIEUNHAP(PHIEUNHAP instance);
    partial void DeletePHIEUNHAP(PHIEUNHAP instance);
    partial void InsertPHIEUXUAT(PHIEUXUAT instance);
    partial void UpdatePHIEUXUAT(PHIEUXUAT instance);
    partial void DeletePHIEUXUAT(PHIEUXUAT instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertXEMAY(XEMAY instance);
    partial void UpdateXEMAY(XEMAY instance);
    partial void DeleteXEMAY(XEMAY instance);
    #endregion
		
		public QuanLyXeMayDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.QuanLyXeMayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyXeMayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyXeMayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyXeMayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyXeMayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUNHAP> CTPHIEUNHAPs
		{
			get
			{
				return this.GetTable<CTPHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUXUAT> CTPHIEUXUATs
		{
			get
			{
				return this.GetTable<CTPHIEUXUAT>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIXE> LOAIXEs
		{
			get
			{
				return this.GetTable<LOAIXE>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUBAOHANH> PHIEUBAOHANHs
		{
			get
			{
				return this.GetTable<PHIEUBAOHANH>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this.GetTable<PHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUXUAT> PHIEUXUATs
		{
			get
			{
				return this.GetTable<PHIEUXUAT>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<XEMAY> XEMAYs
		{
			get
			{
				return this.GetTable<XEMAY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACHUCVU;
		
		private string _TENCHUCVU;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCVUChanging(string value);
    partial void OnMACHUCVUChanged();
    partial void OnTENCHUCVUChanging(string value);
    partial void OnTENCHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(50)")]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this.OnTENCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCVU = value;
					this.SendPropertyChanged("TENCHUCVU");
					this.OnTENCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_NHANVIENs", ThisKey="MACHUCVU", OtherKey="MACHUCVU")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUNHAP")]
	public partial class CTPHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPN;
		
		private string _MAXE;
		
		private System.Nullable<int> _DONGIANHAP;
		
		private System.Nullable<int> _SOLUONGNHAP;
		
		private System.Nullable<double> _THUE;
		
		private System.Nullable<double> _THANHTIENCTPN;
		
		private System.Nullable<int> _SOLUONGDANHAP;
		
		private EntityRef<PHIEUNHAP> _PHIEUNHAP;
		
		private EntityRef<XEMAY> _XEMAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPNChanging(string value);
    partial void OnMAPNChanged();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnDONGIANHAPChanging(System.Nullable<int> value);
    partial void OnDONGIANHAPChanged();
    partial void OnSOLUONGNHAPChanging(System.Nullable<int> value);
    partial void OnSOLUONGNHAPChanged();
    partial void OnTHUEChanging(System.Nullable<double> value);
    partial void OnTHUEChanged();
    partial void OnTHANHTIENCTPNChanging(System.Nullable<double> value);
    partial void OnTHANHTIENCTPNChanged();
    partial void OnSOLUONGDANHAPChanging(System.Nullable<int> value);
    partial void OnSOLUONGDANHAPChanged();
    #endregion
		
		public CTPHIEUNHAP()
		{
			this._PHIEUNHAP = default(EntityRef<PHIEUNHAP>);
			this._XEMAY = default(EntityRef<XEMAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPN
		{
			get
			{
				return this._MAPN;
			}
			set
			{
				if ((this._MAPN != value))
				{
					if (this._PHIEUNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPNChanging(value);
					this.SendPropertyChanging();
					this._MAPN = value;
					this.SendPropertyChanged("MAPN");
					this.OnMAPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					if (this._XEMAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIANHAP", DbType="Int")]
		public System.Nullable<int> DONGIANHAP
		{
			get
			{
				return this._DONGIANHAP;
			}
			set
			{
				if ((this._DONGIANHAP != value))
				{
					this.OnDONGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._DONGIANHAP = value;
					this.SendPropertyChanged("DONGIANHAP");
					this.OnDONGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGNHAP", DbType="Int")]
		public System.Nullable<int> SOLUONGNHAP
		{
			get
			{
				return this._SOLUONGNHAP;
			}
			set
			{
				if ((this._SOLUONGNHAP != value))
				{
					this.OnSOLUONGNHAPChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGNHAP = value;
					this.SendPropertyChanged("SOLUONGNHAP");
					this.OnSOLUONGNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUE", DbType="Float")]
		public System.Nullable<double> THUE
		{
			get
			{
				return this._THUE;
			}
			set
			{
				if ((this._THUE != value))
				{
					this.OnTHUEChanging(value);
					this.SendPropertyChanging();
					this._THUE = value;
					this.SendPropertyChanged("THUE");
					this.OnTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIENCTPN", DbType="Float")]
		public System.Nullable<double> THANHTIENCTPN
		{
			get
			{
				return this._THANHTIENCTPN;
			}
			set
			{
				if ((this._THANHTIENCTPN != value))
				{
					this.OnTHANHTIENCTPNChanging(value);
					this.SendPropertyChanging();
					this._THANHTIENCTPN = value;
					this.SendPropertyChanged("THANHTIENCTPN");
					this.OnTHANHTIENCTPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGDANHAP", DbType="Int")]
		public System.Nullable<int> SOLUONGDANHAP
		{
			get
			{
				return this._SOLUONGDANHAP;
			}
			set
			{
				if ((this._SOLUONGDANHAP != value))
				{
					this.OnSOLUONGDANHAPChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGDANHAP = value;
					this.SendPropertyChanged("SOLUONGDANHAP");
					this.OnSOLUONGDANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAP_CTPHIEUNHAP", Storage="_PHIEUNHAP", ThisKey="MAPN", OtherKey="MAPN", IsForeignKey=true)]
		public PHIEUNHAP PHIEUNHAP
		{
			get
			{
				return this._PHIEUNHAP.Entity;
			}
			set
			{
				PHIEUNHAP previousValue = this._PHIEUNHAP.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAP.Entity = null;
						previousValue.CTPHIEUNHAP = null;
					}
					this._PHIEUNHAP.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUNHAP = this;
						this._MAPN = value.MAPN;
					}
					else
					{
						this._MAPN = default(string);
					}
					this.SendPropertyChanged("PHIEUNHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_CTPHIEUNHAP", Storage="_XEMAY", ThisKey="MAXE", OtherKey="MAXE", IsForeignKey=true)]
		public XEMAY XEMAY
		{
			get
			{
				return this._XEMAY.Entity;
			}
			set
			{
				XEMAY previousValue = this._XEMAY.Entity;
				if (((previousValue != value) 
							|| (this._XEMAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XEMAY.Entity = null;
						previousValue.CTPHIEUNHAPs.Remove(this);
					}
					this._XEMAY.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUNHAPs.Add(this);
						this._MAXE = value.MAXE;
					}
					else
					{
						this._MAXE = default(string);
					}
					this.SendPropertyChanged("XEMAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUXUAT")]
	public partial class CTPHIEUXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAXE;
		
		private string _MAPX;
		
		private EntityRef<PHIEUXUAT> _PHIEUXUAT;
		
		private EntityRef<XEMAY> _XEMAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnMAPXChanging(string value);
    partial void OnMAPXChanged();
    #endregion
		
		public CTPHIEUXUAT()
		{
			this._PHIEUXUAT = default(EntityRef<PHIEUXUAT>);
			this._XEMAY = default(EntityRef<XEMAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					if (this._XEMAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPX", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPX
		{
			get
			{
				return this._MAPX;
			}
			set
			{
				if ((this._MAPX != value))
				{
					if (this._PHIEUXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPXChanging(value);
					this.SendPropertyChanging();
					this._MAPX = value;
					this.SendPropertyChanged("MAPX");
					this.OnMAPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUXUAT_CTPHIEUXUAT", Storage="_PHIEUXUAT", ThisKey="MAPX", OtherKey="MAPX", IsForeignKey=true)]
		public PHIEUXUAT PHIEUXUAT
		{
			get
			{
				return this._PHIEUXUAT.Entity;
			}
			set
			{
				PHIEUXUAT previousValue = this._PHIEUXUAT.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUXUAT.Entity = null;
						previousValue.CTPHIEUXUATs.Remove(this);
					}
					this._PHIEUXUAT.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUXUATs.Add(this);
						this._MAPX = value.MAPX;
					}
					else
					{
						this._MAPX = default(string);
					}
					this.SendPropertyChanged("PHIEUXUAT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_CTPHIEUXUAT", Storage="_XEMAY", ThisKey="MAXE", OtherKey="MAXE", IsForeignKey=true)]
		public XEMAY XEMAY
		{
			get
			{
				return this._XEMAY.Entity;
			}
			set
			{
				XEMAY previousValue = this._XEMAY.Entity;
				if (((previousValue != value) 
							|| (this._XEMAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XEMAY.Entity = null;
						previousValue.CTPHIEUXUATs.Remove(this);
					}
					this._XEMAY.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUXUATs.Add(this);
						this._MAXE = value.MAXE;
					}
					else
					{
						this._MAXE = default(string);
					}
					this.SendPropertyChanged("XEMAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKH;
		
		private string _TENKH;
		
		private string _DIACHIKH;
		
		private string _SDTKH;
		
		private string _EMAILKH;
		
		private string _CMND;
		
		private EntitySet<PHIEUBAOHANH> _PHIEUBAOHANHs;
		
		private EntitySet<PHIEUXUAT> _PHIEUXUATs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnTENKHChanging(string value);
    partial void OnTENKHChanged();
    partial void OnDIACHIKHChanging(string value);
    partial void OnDIACHIKHChanged();
    partial void OnSDTKHChanging(string value);
    partial void OnSDTKHChanged();
    partial void OnEMAILKHChanging(string value);
    partial void OnEMAILKHChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._PHIEUBAOHANHs = new EntitySet<PHIEUBAOHANH>(new Action<PHIEUBAOHANH>(this.attach_PHIEUBAOHANHs), new Action<PHIEUBAOHANH>(this.detach_PHIEUBAOHANHs));
			this._PHIEUXUATs = new EntitySet<PHIEUXUAT>(new Action<PHIEUXUAT>(this.attach_PHIEUXUATs), new Action<PHIEUXUAT>(this.detach_PHIEUXUATs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH", DbType="NVarChar(50)")]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this.OnTENKHChanging(value);
					this.SendPropertyChanging();
					this._TENKH = value;
					this.SendPropertyChanged("TENKH");
					this.OnTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHIKH", DbType="NVarChar(200)")]
		public string DIACHIKH
		{
			get
			{
				return this._DIACHIKH;
			}
			set
			{
				if ((this._DIACHIKH != value))
				{
					this.OnDIACHIKHChanging(value);
					this.SendPropertyChanging();
					this._DIACHIKH = value;
					this.SendPropertyChanged("DIACHIKH");
					this.OnDIACHIKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTKH", DbType="VarChar(20)")]
		public string SDTKH
		{
			get
			{
				return this._SDTKH;
			}
			set
			{
				if ((this._SDTKH != value))
				{
					this.OnSDTKHChanging(value);
					this.SendPropertyChanging();
					this._SDTKH = value;
					this.SendPropertyChanged("SDTKH");
					this.OnSDTKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILKH", DbType="NVarChar(50)")]
		public string EMAILKH
		{
			get
			{
				return this._EMAILKH;
			}
			set
			{
				if ((this._EMAILKH != value))
				{
					this.OnEMAILKHChanging(value);
					this.SendPropertyChanging();
					this._EMAILKH = value;
					this.SendPropertyChanged("EMAILKH");
					this.OnEMAILKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUBAOHANH", Storage="_PHIEUBAOHANHs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<PHIEUBAOHANH> PHIEUBAOHANHs
		{
			get
			{
				return this._PHIEUBAOHANHs;
			}
			set
			{
				this._PHIEUBAOHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUXUAT", Storage="_PHIEUXUATs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<PHIEUXUAT> PHIEUXUATs
		{
			get
			{
				return this._PHIEUXUATs;
			}
			set
			{
				this._PHIEUXUATs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUBAOHANHs(PHIEUBAOHANH entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUBAOHANHs(PHIEUBAOHANH entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_PHIEUXUATs(PHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUXUATs(PHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIXE")]
	public partial class LOAIXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHANG;
		
		private string _TENHANG;
		
		private System.Nullable<int> _DONGIANHAP;
		
		private System.Nullable<int> _DONGIA;
		
		private EntitySet<XEMAY> _XEMAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHANGChanging(string value);
    partial void OnMAHANGChanged();
    partial void OnTENHANGChanging(string value);
    partial void OnTENHANGChanged();
    partial void OnDONGIANHAPChanging(System.Nullable<int> value);
    partial void OnDONGIANHAPChanged();
    partial void OnDONGIAChanging(System.Nullable<int> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public LOAIXE()
		{
			this._XEMAYs = new EntitySet<XEMAY>(new Action<XEMAY>(this.attach_XEMAYs), new Action<XEMAY>(this.detach_XEMAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHANG", DbType="NVarChar(50)")]
		public string TENHANG
		{
			get
			{
				return this._TENHANG;
			}
			set
			{
				if ((this._TENHANG != value))
				{
					this.OnTENHANGChanging(value);
					this.SendPropertyChanging();
					this._TENHANG = value;
					this.SendPropertyChanged("TENHANG");
					this.OnTENHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIANHAP", DbType="Int")]
		public System.Nullable<int> DONGIANHAP
		{
			get
			{
				return this._DONGIANHAP;
			}
			set
			{
				if ((this._DONGIANHAP != value))
				{
					this.OnDONGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._DONGIANHAP = value;
					this.SendPropertyChanged("DONGIANHAP");
					this.OnDONGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Int")]
		public System.Nullable<int> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIXE_XEMAY", Storage="_XEMAYs", ThisKey="MAHANG", OtherKey="MAHANG")]
		public EntitySet<XEMAY> XEMAYs
		{
			get
			{
				return this._XEMAYs;
			}
			set
			{
				this._XEMAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_XEMAYs(XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIXE = this;
		}
		
		private void detach_XEMAYs(XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIXE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _TENNCC;
		
		private string _DIACHINCC;
		
		private string _SDTNCC;
		
		private string _EMAILNCC;
		
		private EntitySet<PHIEUNHAP> _PHIEUNHAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnDIACHINCCChanging(string value);
    partial void OnDIACHINCCChanged();
    partial void OnSDTNCCChanging(string value);
    partial void OnSDTNCCChanged();
    partial void OnEMAILNCCChanging(string value);
    partial void OnEMAILNCCChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._PHIEUNHAPs = new EntitySet<PHIEUNHAP>(new Action<PHIEUNHAP>(this.attach_PHIEUNHAPs), new Action<PHIEUNHAP>(this.detach_PHIEUNHAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(50)")]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHINCC", DbType="NVarChar(200)")]
		public string DIACHINCC
		{
			get
			{
				return this._DIACHINCC;
			}
			set
			{
				if ((this._DIACHINCC != value))
				{
					this.OnDIACHINCCChanging(value);
					this.SendPropertyChanging();
					this._DIACHINCC = value;
					this.SendPropertyChanged("DIACHINCC");
					this.OnDIACHINCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTNCC", DbType="VarChar(50)")]
		public string SDTNCC
		{
			get
			{
				return this._SDTNCC;
			}
			set
			{
				if ((this._SDTNCC != value))
				{
					this.OnSDTNCCChanging(value);
					this.SendPropertyChanging();
					this._SDTNCC = value;
					this.SendPropertyChanged("SDTNCC");
					this.OnSDTNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILNCC", DbType="NVarChar(50)")]
		public string EMAILNCC
		{
			get
			{
				return this._EMAILNCC;
			}
			set
			{
				if ((this._EMAILNCC != value))
				{
					this.OnEMAILNCCChanging(value);
					this.SendPropertyChanging();
					this._EMAILNCC = value;
					this.SendPropertyChanged("EMAILNCC");
					this.OnEMAILNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAP", Storage="_PHIEUNHAPs", ThisKey="MANCC", OtherKey="MANCC")]
		public EntitySet<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this._PHIEUNHAPs;
			}
			set
			{
				this._PHIEUNHAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _MACHUCVU;
		
		private string _TENNV;
		
		private System.Nullable<int> _NAMSINH;
		
		private string _GIOITINH;
		
		private string _DIACHINV;
		
		private string _SDTNV;
		
		private string _EMAILNV;
		
		private System.Nullable<double> _LUONG;
		
		private EntitySet<PHIEUBAOHANH> _PHIEUBAOHANHs;
		
		private EntitySet<PHIEUNHAP> _PHIEUNHAPs;
		
		private EntitySet<PHIEUXUAT> _PHIEUXUATs;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMACHUCVUChanging(string value);
    partial void OnMACHUCVUChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnNAMSINHChanging(System.Nullable<int> value);
    partial void OnNAMSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnDIACHINVChanging(string value);
    partial void OnDIACHINVChanged();
    partial void OnSDTNVChanging(string value);
    partial void OnSDTNVChanged();
    partial void OnEMAILNVChanging(string value);
    partial void OnEMAILNVChanged();
    partial void OnLUONGChanging(System.Nullable<double> value);
    partial void OnLUONGChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHIEUBAOHANHs = new EntitySet<PHIEUBAOHANH>(new Action<PHIEUBAOHANH>(this.attach_PHIEUBAOHANHs), new Action<PHIEUBAOHANH>(this.detach_PHIEUBAOHANHs));
			this._PHIEUNHAPs = new EntitySet<PHIEUNHAP>(new Action<PHIEUNHAP>(this.attach_PHIEUNHAPs), new Action<PHIEUNHAP>(this.detach_PHIEUNHAPs));
			this._PHIEUXUATs = new EntitySet<PHIEUXUAT>(new Action<PHIEUXUAT>(this.attach_PHIEUXUATs), new Action<PHIEUXUAT>(this.detach_PHIEUXUATs));
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMSINH", DbType="Int")]
		public System.Nullable<int> NAMSINH
		{
			get
			{
				return this._NAMSINH;
			}
			set
			{
				if ((this._NAMSINH != value))
				{
					this.OnNAMSINHChanging(value);
					this.SendPropertyChanging();
					this._NAMSINH = value;
					this.SendPropertyChanged("NAMSINH");
					this.OnNAMSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(50)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHINV", DbType="NVarChar(100)")]
		public string DIACHINV
		{
			get
			{
				return this._DIACHINV;
			}
			set
			{
				if ((this._DIACHINV != value))
				{
					this.OnDIACHINVChanging(value);
					this.SendPropertyChanging();
					this._DIACHINV = value;
					this.SendPropertyChanged("DIACHINV");
					this.OnDIACHINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTNV", DbType="VarChar(50)")]
		public string SDTNV
		{
			get
			{
				return this._SDTNV;
			}
			set
			{
				if ((this._SDTNV != value))
				{
					this.OnSDTNVChanging(value);
					this.SendPropertyChanging();
					this._SDTNV = value;
					this.SendPropertyChanged("SDTNV");
					this.OnSDTNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILNV", DbType="NVarChar(50)")]
		public string EMAILNV
		{
			get
			{
				return this._EMAILNV;
			}
			set
			{
				if ((this._EMAILNV != value))
				{
					this.OnEMAILNVChanging(value);
					this.SendPropertyChanging();
					this._EMAILNV = value;
					this.SendPropertyChanged("EMAILNV");
					this.OnEMAILNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONG", DbType="Float")]
		public System.Nullable<double> LUONG
		{
			get
			{
				return this._LUONG;
			}
			set
			{
				if ((this._LUONG != value))
				{
					this.OnLUONGChanging(value);
					this.SendPropertyChanging();
					this._LUONG = value;
					this.SendPropertyChanged("LUONG");
					this.OnLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUBAOHANH", Storage="_PHIEUBAOHANHs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<PHIEUBAOHANH> PHIEUBAOHANHs
		{
			get
			{
				return this._PHIEUBAOHANHs;
			}
			set
			{
				this._PHIEUBAOHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAP", Storage="_PHIEUNHAPs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this._PHIEUNHAPs;
			}
			set
			{
				this._PHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUXUAT", Storage="_PHIEUXUATs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<PHIEUXUAT> PHIEUXUATs
		{
			get
			{
				return this._PHIEUXUATs;
			}
			set
			{
				this._PHIEUXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="MANV", OtherKey="MaNV")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_CHUCVU", ThisKey="MACHUCVU", OtherKey="MACHUCVU", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MACHUCVU = value.MACHUCVU;
					}
					else
					{
						this._MACHUCVU = default(string);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUBAOHANHs(PHIEUBAOHANH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUBAOHANHs(PHIEUBAOHANH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUXUATs(PHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUXUATs(PHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUBAOHANH")]
	public partial class PHIEUBAOHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPBH;
		
		private string _MAXE;
		
		private System.Nullable<System.DateTime> _NGAY;
		
		private string _MANV;
		
		private string _MAKH;
		
		private string _TINHTRANG;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<XEMAY> _XEMAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPBHChanging(string value);
    partial void OnMAPBHChanged();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public PHIEUBAOHANH()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._XEMAY = default(EntityRef<XEMAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPBH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPBH
		{
			get
			{
				return this._MAPBH;
			}
			set
			{
				if ((this._MAPBH != value))
				{
					this.OnMAPBHChanging(value);
					this.SendPropertyChanging();
					this._MAPBH = value;
					this.SendPropertyChanged("MAPBH");
					this.OnMAPBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					if (this._XEMAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY", DbType="Date")]
		public System.Nullable<System.DateTime> NGAY
		{
			get
			{
				return this._NGAY;
			}
			set
			{
				if ((this._NGAY != value))
				{
					this.OnNGAYChanging(value);
					this.SendPropertyChanging();
					this._NGAY = value;
					this.SendPropertyChanged("NGAY");
					this.OnNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(50)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUBAOHANH", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUBAOHANHs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUBAOHANHs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUBAOHANH", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUBAOHANHs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUBAOHANHs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_PHIEUBAOHANH", Storage="_XEMAY", ThisKey="MAXE", OtherKey="MAXE", IsForeignKey=true)]
		public XEMAY XEMAY
		{
			get
			{
				return this._XEMAY.Entity;
			}
			set
			{
				XEMAY previousValue = this._XEMAY.Entity;
				if (((previousValue != value) 
							|| (this._XEMAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XEMAY.Entity = null;
						previousValue.PHIEUBAOHANHs.Remove(this);
					}
					this._XEMAY.Entity = value;
					if ((value != null))
					{
						value.PHIEUBAOHANHs.Add(this);
						this._MAXE = value.MAXE;
					}
					else
					{
						this._MAXE = default(string);
					}
					this.SendPropertyChanged("XEMAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAP")]
	public partial class PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPN;
		
		private string _MANCC;
		
		private string _MANV;
		
		private System.Nullable<System.DateTime> _NGAYNHAP;
		
		private System.Nullable<bool> _THANHTOAN;
		
		private System.Nullable<double> _TONGTIENPN;
		
		private System.Nullable<double> _SOTIENDATRA;
		
		private EntityRef<CTPHIEUNHAP> _CTPHIEUNHAP;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPNChanging(string value);
    partial void OnMAPNChanged();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYNHAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPChanged();
    partial void OnTHANHTOANChanging(System.Nullable<bool> value);
    partial void OnTHANHTOANChanged();
    partial void OnTONGTIENPNChanging(System.Nullable<double> value);
    partial void OnTONGTIENPNChanged();
    partial void OnSOTIENDATRAChanging(System.Nullable<double> value);
    partial void OnSOTIENDATRAChanged();
    #endregion
		
		public PHIEUNHAP()
		{
			this._CTPHIEUNHAP = default(EntityRef<CTPHIEUNHAP>);
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPN
		{
			get
			{
				return this._MAPN;
			}
			set
			{
				if ((this._MAPN != value))
				{
					this.OnMAPNChanging(value);
					this.SendPropertyChanging();
					this._MAPN = value;
					this.SendPropertyChanged("MAPN");
					this.OnMAPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTOAN", DbType="Bit")]
		public System.Nullable<bool> THANHTOAN
		{
			get
			{
				return this._THANHTOAN;
			}
			set
			{
				if ((this._THANHTOAN != value))
				{
					this.OnTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._THANHTOAN = value;
					this.SendPropertyChanged("THANHTOAN");
					this.OnTHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIENPN", DbType="Float")]
		public System.Nullable<double> TONGTIENPN
		{
			get
			{
				return this._TONGTIENPN;
			}
			set
			{
				if ((this._TONGTIENPN != value))
				{
					this.OnTONGTIENPNChanging(value);
					this.SendPropertyChanging();
					this._TONGTIENPN = value;
					this.SendPropertyChanged("TONGTIENPN");
					this.OnTONGTIENPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTIENDATRA", DbType="Float")]
		public System.Nullable<double> SOTIENDATRA
		{
			get
			{
				return this._SOTIENDATRA;
			}
			set
			{
				if ((this._SOTIENDATRA != value))
				{
					this.OnSOTIENDATRAChanging(value);
					this.SendPropertyChanging();
					this._SOTIENDATRA = value;
					this.SendPropertyChanged("SOTIENDATRA");
					this.OnSOTIENDATRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAP_CTPHIEUNHAP", Storage="_CTPHIEUNHAP", ThisKey="MAPN", OtherKey="MAPN", IsUnique=true, IsForeignKey=false)]
		public CTPHIEUNHAP CTPHIEUNHAP
		{
			get
			{
				return this._CTPHIEUNHAP.Entity;
			}
			set
			{
				CTPHIEUNHAP previousValue = this._CTPHIEUNHAP.Entity;
				if (((previousValue != value) 
							|| (this._CTPHIEUNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CTPHIEUNHAP.Entity = null;
						previousValue.PHIEUNHAP = null;
					}
					this._CTPHIEUNHAP.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAP = this;
					}
					this.SendPropertyChanged("CTPHIEUNHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAP", Storage="_NHACUNGCAP", ThisKey="MANCC", OtherKey="MANCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.PHIEUNHAPs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPs.Add(this);
						this._MANCC = value.MANCC;
					}
					else
					{
						this._MANCC = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAP", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUNHAPs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUXUAT")]
	public partial class PHIEUXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPX;
		
		private string _MANV;
		
		private string _MAKH;
		
		private System.Nullable<System.DateTime> _NGAYXUAT;
		
		private System.Nullable<double> _TONGTIENPX;
		
		private string _TRANGTHAI;
		
		private EntitySet<CTPHIEUXUAT> _CTPHIEUXUATs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPXChanging(string value);
    partial void OnMAPXChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnNGAYXUATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYXUATChanged();
    partial void OnTONGTIENPXChanging(System.Nullable<double> value);
    partial void OnTONGTIENPXChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public PHIEUXUAT()
		{
			this._CTPHIEUXUATs = new EntitySet<CTPHIEUXUAT>(new Action<CTPHIEUXUAT>(this.attach_CTPHIEUXUATs), new Action<CTPHIEUXUAT>(this.detach_CTPHIEUXUATs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPX", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPX
		{
			get
			{
				return this._MAPX;
			}
			set
			{
				if ((this._MAPX != value))
				{
					this.OnMAPXChanging(value);
					this.SendPropertyChanging();
					this._MAPX = value;
					this.SendPropertyChanged("MAPX");
					this.OnMAPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYXUAT", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYXUAT
		{
			get
			{
				return this._NGAYXUAT;
			}
			set
			{
				if ((this._NGAYXUAT != value))
				{
					this.OnNGAYXUATChanging(value);
					this.SendPropertyChanging();
					this._NGAYXUAT = value;
					this.SendPropertyChanged("NGAYXUAT");
					this.OnNGAYXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIENPX", DbType="Float")]
		public System.Nullable<double> TONGTIENPX
		{
			get
			{
				return this._TONGTIENPX;
			}
			set
			{
				if ((this._TONGTIENPX != value))
				{
					this.OnTONGTIENPXChanging(value);
					this.SendPropertyChanging();
					this._TONGTIENPX = value;
					this.SendPropertyChanged("TONGTIENPX");
					this.OnTONGTIENPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUXUAT_CTPHIEUXUAT", Storage="_CTPHIEUXUATs", ThisKey="MAPX", OtherKey="MAPX")]
		public EntitySet<CTPHIEUXUAT> CTPHIEUXUATs
		{
			get
			{
				return this._CTPHIEUXUATs;
			}
			set
			{
				this._CTPHIEUXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUXUAT", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUXUATs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUATs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUXUAT", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUXUATs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUATs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUXUATs(CTPHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUXUAT = this;
		}
		
		private void detach_CTPHIEUXUATs(CTPHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUXUAT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _TrangThai;
		
		private string _CapQuyen;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnCapQuyenChanging(string value);
    partial void OnCapQuyenChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(10)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapQuyen", DbType="NVarChar(50)")]
		public string CapQuyen
		{
			get
			{
				return this._CapQuyen;
			}
			set
			{
				if ((this._CapQuyen != value))
				{
					this.OnCapQuyenChanging(value);
					this.SendPropertyChanging();
					this._CapQuyen = value;
					this.SendPropertyChanged("CapQuyen");
					this.OnCapQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._MaNV = value.MANV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XEMAY")]
	public partial class XEMAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAXE;
		
		private string _TENXE;
		
		private string _MAUSAC;
		
		private string _MAHANG;
		
		private string _TRANGTHAI;
		
		private System.Nullable<int> _THOIGIANBH;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntitySet<CTPHIEUNHAP> _CTPHIEUNHAPs;
		
		private EntitySet<CTPHIEUXUAT> _CTPHIEUXUATs;
		
		private EntitySet<PHIEUBAOHANH> _PHIEUBAOHANHs;
		
		private EntityRef<LOAIXE> _LOAIXE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnTENXEChanging(string value);
    partial void OnTENXEChanged();
    partial void OnMAUSACChanging(string value);
    partial void OnMAUSACChanged();
    partial void OnMAHANGChanging(string value);
    partial void OnMAHANGChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    partial void OnTHOIGIANBHChanging(System.Nullable<int> value);
    partial void OnTHOIGIANBHChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public XEMAY()
		{
			this._CTPHIEUNHAPs = new EntitySet<CTPHIEUNHAP>(new Action<CTPHIEUNHAP>(this.attach_CTPHIEUNHAPs), new Action<CTPHIEUNHAP>(this.detach_CTPHIEUNHAPs));
			this._CTPHIEUXUATs = new EntitySet<CTPHIEUXUAT>(new Action<CTPHIEUXUAT>(this.attach_CTPHIEUXUATs), new Action<CTPHIEUXUAT>(this.detach_CTPHIEUXUATs));
			this._PHIEUBAOHANHs = new EntitySet<PHIEUBAOHANH>(new Action<PHIEUBAOHANH>(this.attach_PHIEUBAOHANHs), new Action<PHIEUBAOHANH>(this.detach_PHIEUBAOHANHs));
			this._LOAIXE = default(EntityRef<LOAIXE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENXE", DbType="NVarChar(50)")]
		public string TENXE
		{
			get
			{
				return this._TENXE;
			}
			set
			{
				if ((this._TENXE != value))
				{
					this.OnTENXEChanging(value);
					this.SendPropertyChanging();
					this._TENXE = value;
					this.SendPropertyChanged("TENXE");
					this.OnTENXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAUSAC", DbType="NVarChar(50)")]
		public string MAUSAC
		{
			get
			{
				return this._MAUSAC;
			}
			set
			{
				if ((this._MAUSAC != value))
				{
					this.OnMAUSACChanging(value);
					this.SendPropertyChanging();
					this._MAUSAC = value;
					this.SendPropertyChanged("MAUSAC");
					this.OnMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					if (this._LOAIXE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANBH", DbType="Int")]
		public System.Nullable<int> THOIGIANBH
		{
			get
			{
				return this._THOIGIANBH;
			}
			set
			{
				if ((this._THOIGIANBH != value))
				{
					this.OnTHOIGIANBHChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANBH = value;
					this.SendPropertyChanged("THOIGIANBH");
					this.OnTHOIGIANBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_CTPHIEUNHAP", Storage="_CTPHIEUNHAPs", ThisKey="MAXE", OtherKey="MAXE")]
		public EntitySet<CTPHIEUNHAP> CTPHIEUNHAPs
		{
			get
			{
				return this._CTPHIEUNHAPs;
			}
			set
			{
				this._CTPHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_CTPHIEUXUAT", Storage="_CTPHIEUXUATs", ThisKey="MAXE", OtherKey="MAXE")]
		public EntitySet<CTPHIEUXUAT> CTPHIEUXUATs
		{
			get
			{
				return this._CTPHIEUXUATs;
			}
			set
			{
				this._CTPHIEUXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_PHIEUBAOHANH", Storage="_PHIEUBAOHANHs", ThisKey="MAXE", OtherKey="MAXE")]
		public EntitySet<PHIEUBAOHANH> PHIEUBAOHANHs
		{
			get
			{
				return this._PHIEUBAOHANHs;
			}
			set
			{
				this._PHIEUBAOHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIXE_XEMAY", Storage="_LOAIXE", ThisKey="MAHANG", OtherKey="MAHANG", IsForeignKey=true)]
		public LOAIXE LOAIXE
		{
			get
			{
				return this._LOAIXE.Entity;
			}
			set
			{
				LOAIXE previousValue = this._LOAIXE.Entity;
				if (((previousValue != value) 
							|| (this._LOAIXE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIXE.Entity = null;
						previousValue.XEMAYs.Remove(this);
					}
					this._LOAIXE.Entity = value;
					if ((value != null))
					{
						value.XEMAYs.Add(this);
						this._MAHANG = value.MAHANG;
					}
					else
					{
						this._MAHANG = default(string);
					}
					this.SendPropertyChanged("LOAIXE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUNHAPs(CTPHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = this;
		}
		
		private void detach_CTPHIEUNHAPs(CTPHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = null;
		}
		
		private void attach_CTPHIEUXUATs(CTPHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = this;
		}
		
		private void detach_CTPHIEUXUATs(CTPHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = null;
		}
		
		private void attach_PHIEUBAOHANHs(PHIEUBAOHANH entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = this;
		}
		
		private void detach_PHIEUBAOHANHs(PHIEUBAOHANH entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = null;
		}
	}
}
#pragma warning restore 1591
